name: Update Wallpaper Gallery

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update markdown gallery
        run: |
          python update_readme.py

      - name: Save changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md

          # commit only if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update wallpaper gallery"
            git push
          else
            echo "No changes to commit."
          fi